eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka
spring:
  application:
      name: article
  datasource:
    password:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: com.tian.article.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: com.tian.article.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的时候，判断表达式username != null 是否追加username ！= ''
  identity: MYSQL